use sha2::{Digest, Sha256};

use crate::application::{CoreDistributionPort, PortError};
use crate::domain::{ContentHash, CoreDistribution, DistributionFile, RelativePath};

/// `(destination, bytes)` for every file in `scripts/harness-install-files.txt`,
/// generated by `build.rs`.
const CORE_PAYLOAD: &[(&str, &[u8])] = include!(concat!(env!("OUT_DIR"), "/core_payload.rs"));

#[derive(Clone, Copy, Default)]
pub struct EmbeddedCoreDistribution;

impl CoreDistributionPort for EmbeddedCoreDistribution {
    fn current(&self) -> Result<CoreDistribution, PortError> {
        let mut files = Vec::new();
        for (path, content) in CORE_PAYLOAD {
            add(&mut files, path, content)?;
        }
        Ok(CoreDistribution {
            version: env!("CARGO_PKG_VERSION").to_owned(),
            files,
        })
    }
}

fn add(files: &mut Vec<DistributionFile>, path: &str, content: &[u8]) -> Result<(), PortError> {
    let path = RelativePath::parse(path).map_err(|error| PortError::new(error.to_string()))?;
    let hash = ContentHash::parse(format!("{:x}", Sha256::digest(content)))
        .map_err(|error| PortError::new(error.to_string()))?;
    files.push(DistributionFile {
        path,
        content: content.to_vec(),
        hash,
    });
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_payload_is_generic_and_complete() {
        let distribution = EmbeddedCoreDistribution.current().unwrap();
        distribution.validate().unwrap();
        let embedded_paths = distribution
            .files
            .iter()
            .map(|file| file.path.as_str())
            .collect::<std::collections::BTreeSet<_>>();
        let manifest = include_str!("../../../../scripts/harness-install-files.txt")
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty() && !line.starts_with('#'))
            .map(|line| {
                line.split_once("<-")
                    .map_or((line, line), |(d, s)| (d.trim(), s.trim()))
            })
            .collect::<Vec<_>>();
        let manifest_paths = manifest
            .iter()
            .map(|(destination, _)| *destination)
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(embedded_paths, manifest_paths);
        let repository = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        for (destination, source) in manifest {
            if source.starts_with("compose:") {
                continue;
            }
            let embedded = distribution
                .files
                .iter()
                .find(|file| file.path.as_str() == destination)
                .unwrap();
            assert_eq!(
                embedded.content,
                std::fs::read(repository.join(source)).unwrap(),
                "{destination} differs from its manifest source {source}"
            );
        }
        let agents = distribution
            .files
            .iter()
            .find(|file| file.path.as_str() == "AGENTS.md")
            .unwrap();
        let agents = String::from_utf8(agents.content.clone()).unwrap();
        assert!(agents.contains("No control-plane operation is required."));
        assert!(!agents.contains("Current Upstream Goal"));
        let plans = distribution
            .files
            .iter()
            .find(|file| file.path.as_str() == "docs/plans/README.md")
            .unwrap();
        assert!(!String::from_utf8_lossy(&plans.content).contains("rust-harness-core"));
        for skill in [
            ".agents/skills/onboard-repository/SKILL.md",
            ".agents/skills/audit-onboarding-proposal/SKILL.md",
            ".agents/skills/encode-invariant/SKILL.md",
            ".agents/skills/improve-harness/SKILL.md",
        ] {
            let skill = distribution
                .files
                .iter()
                .find(|file| file.path.as_str() == skill)
                .unwrap();
            let skill = String::from_utf8_lossy(&skill.content);
            assert!(skill.contains("authorized") || skill.contains("read-only"));
        }
        for metadata in [
            ".agents/skills/onboard-repository/agents/openai.yaml",
            ".agents/skills/audit-onboarding-proposal/agents/openai.yaml",
            ".agents/skills/improve-harness/agents/openai.yaml",
        ] {
            let metadata = distribution
                .files
                .iter()
                .find(|file| file.path.as_str() == metadata)
                .unwrap();
            assert!(String::from_utf8_lossy(&metadata.content)
                .contains("allow_implicit_invocation: false"));
        }
        let invariant_metadata = distribution
            .files
            .iter()
            .find(|file| file.path.as_str() == ".agents/skills/encode-invariant/agents/openai.yaml")
            .unwrap();
        assert!(String::from_utf8_lossy(&invariant_metadata.content)
            .contains("allow_implicit_invocation: true"));
        let migrate_metadata = distribution
            .files
            .iter()
            .find(|file| file.path.as_str() == ".agents/skills/migrate-harness/agents/openai.yaml")
            .unwrap();
        assert!(String::from_utf8_lossy(&migrate_metadata.content)
            .contains("allow_implicit_invocation: true"));
        let migrate = distribution
            .files
            .iter()
            .find(|file| file.path.as_str() == ".agents/skills/migrate-harness/SKILL.md")
            .unwrap();
        assert!(String::from_utf8_lossy(&migrate.content).contains("Never delete"));
    }

    #[test]
    fn embedded_payload_uses_lf_line_endings_on_every_platform() {
        for file in EmbeddedCoreDistribution.current().unwrap().files {
            assert!(
                !file.content.contains(&b'\r'),
                "{} embeds a carriage return; the build checkout must honor .gitattributes eol=lf",
                file.path
            );
        }
    }
}
